; Invoker Game Bot — тексты интерфейса (RU / EN / ES / 中文).
; Часть invoker_bot.ahk (подключается через #Include), сам по себе не запускается.

; ---------------- языки ----------------
LangCodes  := ["ru", "en", "es", "zh"]
LangLabels := ["RU", "EN", "ES", "中"]
Strings := Map(
    "ru", Map(
        "title", "Invoker бот", "subtitle", "invoker-game.com · New / Old",
        "update", "⬆ Версия {} — обновить в один клик", "updLoading", "Скачиваю версию {}…", "updFail", "Не получилось обновиться — открываю страницу релиза",
        "author", "Бот написан {}",
        "modeLbl", "РЕЖИМ", "modeBot", "Бот", "modeCoach", "Тренер", "modeDrill", "Тренировка",
        "drillLbl", "ТРЕНИРОВКА БЕЗ САЙТА", "weakOnly", "Только мои слабые спеллы",
        "startDrill", "▶   ТРЕНИРОВКА", "hintDrill", "Тренировка: нажми {}, собирай шары`nи жми R — программа засекает время",
        "drillTitle", "Тренировка", "drillReady", "Пробел — начать  ·  Esc — закрыть",
        "drillAll", "все спеллы", "drillWeak", "слабые спеллы", "drillPrompt", "Собери шары и нажми {}",
        "drillWrong", "Не тот спелл", "drillOk", "Есть!", "drillHint", "Подсказка",
        "drillDone", "Готово!", "drillAvg", "в среднем {} сек на спелл", "drillErr", "ошибок",
        "drillAgain", "Пробел — ещё раз  ·  Esc — закрыть", "drillSlow", "Дольше всего",
        "drillNoData", "Статистики пока нет — тренируем все спеллы", "drillRun", "Тренировка идёт…",
        "kindDrill", "Тренировка", "drillIcons", "Загружаю иконки спеллов…", "ovReset", "Сбросить место и размер оверлея",
        "sndTitle", "Звук в конце прогона", "sndVolume", "Громкость", "snd_chime", "Колокольчик", "snd_bell", "Колокол", "snd_arcade", "Аркада", "snd_soft", "Мягкий", "snd_invoke", "Invoke", "snd_windows", "Звук Windows", "snd_custom", "Свой файл…",
        "chartTitle", "Прогресс: секунды на спелл", "chartEmpty", "Сыграй с тренером или потренируйся — здесь появится график", "perSpell", "сек/спелл",
        "speed", "СКОРОСТЬ", "segTime", "Своё время", "segFast", "Макс. скорость",
        "perGame", "сек на игру", "options", "ОПЦИИ",
        "jitter", "Человеческие паузы (±25%)", "repeat", "Играть по кругу",
        "sound", "Сигнал, когда прогон закончен", "hotkey", "Клавиша старт / стоп",
        "keys", "КЛАВИШИ (если менял на сайте)",
        "start", "▶   СТАРТ", "startCoach", "▶   ТРЕНЕР", "stop", "■   СТОП",
        "stats", "Статистика", "tray", "Свернуть в трей",
        "hint", "Открой invoker-game.com и нажми {}",
        "hintCoach", "Тренер: открой invoker-game.com, нажми {},`nпотом Start на сайте — буду подсказывать",
        "running", "Запущен. Переключись на вкладку игры…",
        "waitTab", "Жду вкладку invoker-game.com…`n(открой её в браузере)",
        "noGame", "Не вижу игру на странице…",
        "coachWait", "Тренер готов. Нажми Start Game (Enter) на сайте",
        "unknown", "Неизвестный спелл: ",
        "done", "Готово! Время на сайте: ",
        "again", "Пройдено за {}. Заново…",
        "stopped", "Остановлен", "badTime", "Время введено неправильно",
        "mode", "Режим", "spell", "Спелл", "time", "Время", "sec", "сек",
        "pressKey", "…", "badKey", "Эта клавиша занята — выбери другую",
        "statsTitle", "Статистика", "colDate", "Дата", "colKind", "Режим",
        "colMode", "Игра", "colTarget", "Цель", "colTime", "Время", "colRank", "Ранг",
        "kindBot", "Бот", "kindCoach", "Тренер", "fastShort", "макс.",
        "best", "Лучшее время", "slowest", "Самые медленные спеллы",
        "noStats", "Пока нет ни одного прогона", "clear", "Очистить", "close", "Закрыть",
        "clearConfirm", "Удалить всю статистику?",
        "trayShow", "Показать окно", "trayToggle", "Старт / стоп", "trayExit", "Выход",
        "trayTip", "Бот свёрнут в трей. Клик по значку — открыть окно."),
    "en", Map(
        "title", "Invoker Bot", "subtitle", "invoker-game.com · New / Old",
        "update", "⬆ Version {} — update in one click", "updLoading", "Downloading version {}…", "updFail", "Update failed, opening the release page",
        "author", "Bot made by {}",
        "modeLbl", "MODE", "modeBot", "Bot", "modeCoach", "Coach", "modeDrill", "Practice",
        "drillLbl", "PRACTICE WITHOUT THE SITE", "weakOnly", "Only my weak spells",
        "startDrill", "▶   PRACTICE", "hintDrill", "Practice: press {}, build the orbs`nand press R, the app times you",
        "drillTitle", "Practice", "drillReady", "Space to start  ·  Esc to close",
        "drillAll", "all spells", "drillWeak", "weak spells", "drillPrompt", "Build the orbs and press {}",
        "drillWrong", "Wrong spell", "drillOk", "Nice!", "drillHint", "Hint",
        "drillDone", "Done!", "drillAvg", "{} sec per spell on average", "drillErr", "mistakes",
        "drillAgain", "Space to go again  ·  Esc to close", "drillSlow", "Slowest",
        "drillNoData", "No statistics yet, practising all spells", "drillRun", "Practice is running…",
        "kindDrill", "Practice", "drillIcons", "Loading spell icons…", "ovReset", "Reset overlay position and size",
        "sndTitle", "Sound when a run is finished", "sndVolume", "Volume", "snd_chime", "Chime", "snd_bell", "Bell", "snd_arcade", "Arcade", "snd_soft", "Soft", "snd_invoke", "Invoke", "snd_windows", "Windows sound", "snd_custom", "Your own file…",
        "chartTitle", "Progress: seconds per spell", "chartEmpty", "Play with the coach or practice, and your chart shows up here", "perSpell", "sec/spell",
        "speed", "SPEED", "segTime", "Custom time", "segFast", "Max speed",
        "perGame", "sec per game", "options", "OPTIONS",
        "jitter", "Human-like pauses (±25%)", "repeat", "Play in a loop",
        "sound", "Beep when a run is finished", "hotkey", "Start / stop key",
        "keys", "KEYS (if you rebound them on the site)",
        "start", "▶   START", "startCoach", "▶   COACH", "stop", "■   STOP",
        "stats", "Statistics", "tray", "Minimize to tray",
        "hint", "Open invoker-game.com and press {}",
        "hintCoach", "Coach: open invoker-game.com, press {},`nthen Start on the site, and I'll show the combos",
        "running", "Running. Switch to the game tab…",
        "waitTab", "Waiting for the invoker-game.com tab…`n(open it in your browser)",
        "noGame", "Can't see the game on the page…",
        "coachWait", "Coach is ready. Press Start Game (Enter) on the site",
        "unknown", "Unknown spell: ",
        "done", "Done! Site time: ",
        "again", "Finished in {}. Restarting…",
        "stopped", "Stopped", "badTime", "Invalid time value",
        "mode", "Mode", "spell", "Spell", "time", "Time", "sec", "sec",
        "pressKey", "…", "badKey", "That key is already used, pick another one",
        "statsTitle", "Statistics", "colDate", "Date", "colKind", "Mode",
        "colMode", "Game", "colTarget", "Target", "colTime", "Time", "colRank", "Rank",
        "kindBot", "Bot", "kindCoach", "Coach", "fastShort", "max",
        "best", "Best time", "slowest", "Slowest spells",
        "noStats", "No runs yet", "clear", "Clear", "close", "Close",
        "clearConfirm", "Delete all statistics?",
        "trayShow", "Show window", "trayToggle", "Start / stop", "trayExit", "Exit",
        "trayTip", "The bot is in the tray. Click the icon to open the window."),
    "es", Map(
        "title", "Bot de Invoker", "subtitle", "invoker-game.com · New / Old",
        "update", "⬆ Versión {} — actualizar con un clic", "updLoading", "Descargando la versión {}…", "updFail", "No se pudo actualizar; abro la página de la versión",
        "author", "Bot creado por {}",
        "modeLbl", "MODO", "modeBot", "Bot", "modeCoach", "Entrenador", "modeDrill", "Práctica",
        "drillLbl", "PRÁCTICA SIN EL SITIO", "weakOnly", "Solo mis hechizos débiles",
        "startDrill", "▶   PRÁCTICA", "hintDrill", "Práctica: pulsa {}, junta los orbes`ny pulsa R; la app mide tu tiempo",
        "drillTitle", "Práctica", "drillReady", "Espacio para empezar  ·  Esc para cerrar",
        "drillAll", "todos los hechizos", "drillWeak", "hechizos débiles", "drillPrompt", "Junta los orbes y pulsa {}",
        "drillWrong", "Hechizo incorrecto", "drillOk", "¡Bien!", "drillHint", "Pista",
        "drillDone", "¡Listo!", "drillAvg", "{} seg por hechizo de media", "drillErr", "errores",
        "drillAgain", "Espacio para repetir  ·  Esc para cerrar", "drillSlow", "Más lentos",
        "drillNoData", "Aún no hay estadísticas, practicamos todos los hechizos", "drillRun", "Práctica en curso…",
        "kindDrill", "Práctica", "drillIcons", "Cargando los iconos de hechizos…", "ovReset", "Restablecer posición y tamaño de la superposición",
        "sndTitle", "Sonido al terminar la partida", "sndVolume", "Volumen", "snd_chime", "Campanilla", "snd_bell", "Campana", "snd_arcade", "Arcade", "snd_soft", "Suave", "snd_invoke", "Invoke", "snd_windows", "Sonido de Windows", "snd_custom", "Tu propio archivo…",
        "chartTitle", "Progreso: segundos por hechizo", "chartEmpty", "Juega con el entrenador o practica y aquí aparecerá tu gráfico", "perSpell", "seg/hechizo",
        "speed", "VELOCIDAD", "segTime", "Tiempo propio", "segFast", "Máx. velocidad",
        "perGame", "seg por partida", "options", "OPCIONES",
        "jitter", "Pausas humanas (±25%)", "repeat", "Jugar en bucle",
        "sound", "Pitido al terminar la partida", "hotkey", "Tecla iniciar / detener",
        "keys", "TECLAS (si las cambiaste en el sitio)",
        "start", "▶   INICIAR", "startCoach", "▶   ENTRENADOR", "stop", "■   DETENER",
        "stats", "Estadísticas", "tray", "Minimizar a la bandeja",
        "hint", "Abre invoker-game.com y pulsa {}",
        "hintCoach", "Entrenador: abre invoker-game.com, pulsa {}`ny luego Start en el sitio; te mostraré los combos",
        "running", "En marcha. Cambia a la pestaña del juego…",
        "waitTab", "Esperando la pestaña de invoker-game.com…`n(ábrela en el navegador)",
        "noGame", "No veo el juego en la página…",
        "coachWait", "Entrenador listo. Pulsa Start Game (Enter) en el sitio",
        "unknown", "Hechizo desconocido: ",
        "done", "¡Listo! Tiempo en el sitio: ",
        "again", "Completado en {}. Reiniciando…",
        "stopped", "Detenido", "badTime", "Tiempo no válido",
        "mode", "Modo", "spell", "Hechizo", "time", "Tiempo", "sec", "seg",
        "pressKey", "…", "badKey", "Esa tecla ya está en uso, elige otra",
        "statsTitle", "Estadísticas", "colDate", "Fecha", "colKind", "Modo",
        "colMode", "Juego", "colTarget", "Objetivo", "colTime", "Tiempo", "colRank", "Rango",
        "kindBot", "Bot", "kindCoach", "Entrenador", "fastShort", "máx.",
        "best", "Mejor tiempo", "slowest", "Hechizos más lentos",
        "noStats", "Todavía no hay partidas", "clear", "Borrar", "close", "Cerrar",
        "clearConfirm", "¿Borrar todas las estadísticas?",
        "trayShow", "Mostrar ventana", "trayToggle", "Iniciar / detener", "trayExit", "Salir",
        "trayTip", "El bot está en la bandeja. Haz clic en el icono para abrir la ventana."),
    "zh", Map(
        "title", "Invoker 机器人", "subtitle", "invoker-game.com · New / Old",
        "update", "⬆ 新版本 {} — 一键更新", "updLoading", "正在下载版本 {}…", "updFail", "更新失败，正在打开发布页面",
        "author", "作者：{}",
        "modeLbl", "模式", "modeBot", "机器人", "modeCoach", "教练", "modeDrill", "练习",
        "drillLbl", "离线练习（不需要网站）", "weakOnly", "只练我的弱项技能",
        "startDrill", "▶   练习", "hintDrill", "练习：按 {}，切好元素球再按 R，`n程序会为你计时",
        "drillTitle", "练习", "drillReady", "空格 开始  ·  Esc 关闭",
        "drillAll", "全部技能", "drillWeak", "弱项技能", "drillPrompt", "切好元素球后按 {}",
        "drillWrong", "技能不对", "drillOk", "不错！", "drillHint", "提示",
        "drillDone", "完成！", "drillAvg", "平均每个技能 {} 秒", "drillErr", "失误",
        "drillAgain", "空格 再来一次  ·  Esc 关闭", "drillSlow", "最慢",
        "drillNoData", "还没有统计数据，练习全部技能", "drillRun", "练习中…",
        "kindDrill", "练习", "drillIcons", "正在加载技能图标…", "ovReset", "重置浮窗的位置和大小",
        "sndTitle", "完成时的提示音", "sndVolume", "音量", "snd_chime", "风铃", "snd_bell", "钟声", "snd_arcade", "街机", "snd_soft", "柔和", "snd_invoke", "祈唤", "snd_windows", "Windows 提示音", "snd_custom", "自定义文件…",
        "chartTitle", "进步：每个技能的秒数", "chartEmpty", "用教练模式或练习模式玩几局，这里就会出现图表", "perSpell", "秒/技能",
        "speed", "速度", "segTime", "自定义用时", "segFast", "最快速度",
        "perGame", "秒 / 整局", "options", "选项",
        "jitter", "模拟人类的间隔（±25%）", "repeat", "循环游戏",
        "sound", "完成时提示音", "hotkey", "开始 / 停止 快捷键",
        "keys", "按键（如果你在网站上改过键位）",
        "start", "▶   开始", "startCoach", "▶   教练", "stop", "■   停止",
        "stats", "统计", "tray", "最小化到托盘",
        "hint", "打开 invoker-game.com 后按 {}",
        "hintCoach", "教练：打开 invoker-game.com，按 {}，`n然后在网站上点 Start，我会提示组合",
        "running", "运行中。请切换到游戏标签页…",
        "waitTab", "正在等待 invoker-game.com 标签页…`n（请在浏览器中打开）",
        "noGame", "页面上找不到游戏…",
        "coachWait", "教练已就绪。请在网站上点 Start Game（回车）",
        "unknown", "未知技能：",
        "done", "完成！网站计时：",
        "again", "用时 {}。正在重新开始…",
        "stopped", "已停止", "badTime", "时间格式不正确",
        "mode", "模式", "spell", "技能", "time", "用时", "sec", "秒",
        "pressKey", "…", "badKey", "该按键已被占用，请换一个",
        "statsTitle", "统计", "colDate", "日期", "colKind", "模式",
        "colMode", "游戏", "colTarget", "目标", "colTime", "用时", "colRank", "段位",
        "kindBot", "机器人", "kindCoach", "教练", "fastShort", "最快",
        "best", "最佳成绩", "slowest", "最慢的技能",
        "noStats", "还没有任何记录", "clear", "清空", "close", "关闭",
        "clearConfirm", "删除全部统计？",
        "trayShow", "显示窗口", "trayToggle", "开始 / 停止", "trayExit", "退出",
        "trayTip", "机器人已最小化到托盘，点击图标打开窗口。")
)
